const DATA=window.AURORA_EP;
const $=s=>document.querySelector(s); const storeKey=`aurora_ep${DATA.meta.num}_test_v1`; const sharedKey='aurora_season_shared_v1';
let state={},historyStack=[],speaking=false;
function defaults(){return Object.assign({name:'Julia',current:'prolog',step:0,ending:null},DATA.defaults||{})}
function conditions(text){if(!text)return '';text=text.replace(/\{\{IFNOT:([\w_]+)\}\}([\s\S]*?)\{\{ENDIF\}\}/g,(_,k,a)=>!state[k]?a:'');text=text.replace(/\{\{IF:([\w_]+)\}\}([\s\S]*?)(?:\{\{ELSE\}\}([\s\S]*?))?\{\{ENDIF\}\}/g,(_,k,a,b)=>state[k]?a:(b||''));return text}
function mdToHtml(md){md=conditions(md).replaceAll('{{name}}',state.name||'Julia');return md.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean).map(block=>{let quote=false;if(block.split('\n').every(l=>l.trim().startsWith('>'))){quote=true;block=block.split('\n').map(l=>l.replace(/^\s*>\s?/, '')).join('<br>')}else block=block.split('\n').join('<br>');block=block.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\*(.*?)\*/g,'<em>$1</em>');return quote?`<blockquote>${block}</blockquote>`:`<p>${block}</p>`}).join('')}
function bgFor(id,time=''){let c='corridor';const s=(id+' '+time).toLowerCase();if(/pokój|room/.test(s))c='room';if(/monitoring|kamera/.test(s))c='monitoring';if(/recepcja|lobby|restaur/.test(s))c='lobby';if(/lustro|mirror/.test(s))c='mirror';if(/piwnic|podziem|kotłown|archiwum/.test(s))c='basement';if(/archiw|akta|kartotek/.test(s))c='archive';if(/pożar|ogień|dym|00:29/.test(s)&&DATA.meta.num>=5)c='fire';if(/świt|rano|05:|06:/.test(s))c='dawn';$('#bg').className='bg '+c}
function save(){localStorage.setItem(storeKey,JSON.stringify({state,historyStack}));}
function restore(){try{const x=JSON.parse(localStorage.getItem(storeKey));if(x?.state){state=x.state;historyStack=x.historyStack||[];return true}}catch{}return false}
function shared(){try{return JSON.parse(localStorage.getItem(sharedKey))||{}}catch{return {}}}
function saveShared(){const sh=shared();Object.assign(sh,state.sharedOut||{},DATA.sharedMap?Object.fromEntries(Object.entries(DATA.sharedMap).map(([out,k])=>[out,state[k]])):{});sh.name=state.name;sh.lastEpisode=DATA.meta.num;sh[`ep${DATA.meta.num}_ending`]=state.ending;localStorage.setItem(sharedKey,JSON.stringify(sh))}
function initStart(){const sel=$('#endingSelect');DATA.startOptions.forEach(o=>{const op=document.createElement('option');op.value=o.value;op.textContent=o.label;sel.appendChild(op)});const sh=shared();if(sh.name)$('#nameInput').value=sh.name;const expected=DATA.meta.num-1;if(sh.lastEpisode===expected&&sh[`ep${expected}_ending`]){const v=sh[`ep${expected}_ending`];if([...sel.options].some(o=>o.value===v))sel.value=v}renderFlags(sel.value);sel.onchange=()=>renderFlags(sel.value)}
function renderFlags(preset){const box=$('#flagBox');box.innerHTML='';const base=Object.assign({},DATA.presets[preset]||{});const sh=shared();(DATA.flags||[]).forEach(f=>{const lab=document.createElement('label');lab.className='check';const inp=document.createElement('input');inp.type='checkbox';inp.id='flag_'+f.key;const sv=sh[f.key];inp.checked=sv!==undefined?!!sv:!!base[f.key];lab.append(inp,document.createTextNode(' '+f.label));box.appendChild(lab)})}
function startNew(){state=defaults();historyStack=[];state.name=$('#nameInput').value.trim()||'Julia';state.prev=$('#endingSelect').value;(DATA.flags||[]).forEach(f=>state[f.key]=$('#flag_'+f.key)?.checked||false);Object.assign(state,DATA.presets[state.prev]||{},Object.fromEntries((DATA.flags||[]).map(f=>[f.key,$('#flag_'+f.key)?.checked||false])));state.current='prolog';showStory();render();save()}
function showStory(){$('#startScreen').classList.add('hidden');$('#endScreen').classList.add('hidden');$('#storyScreen').classList.remove('hidden');window.scrollTo(0,0)}function showStart(){stopSpeech();$('#storyScreen').classList.add('hidden');$('#endScreen').classList.add('hidden');$('#startScreen').classList.remove('hidden');window.scrollTo(0,0)}
function currentNode(){if(state.current==='prolog')return DATA.prologs[state.prev]||DATA.prologs.default;return DATA.scenes[state.current]}
function visibleChoice(c){if(!c.hiddenUnless)return true;if(Array.isArray(c.hiddenUnless))return c.hiddenUnless.every(k=>state[k]);return !!state[c.hiddenUnless]}
function render(){stopSpeech();const n=currentNode();if(!n)return;$('#timeLabel').textContent=n.time||'';$('#sceneLabel').textContent=state.current==='prolog'?`PO ODCINKU ${DATA.meta.num-1}`:state.current.toUpperCase();$('#storyText').innerHTML=mdToHtml(n.text);$('#choices').innerHTML='';const list=(DATA.choices[state.current]||[]).filter(visibleChoice);if(list.length){for(const c of list){const b=document.createElement('button');b.className='choice'+(c.secret?' secret':'');b.innerHTML=`<b>${c.label}</b><small>${c.detail||''}</small>`;b.onclick=()=>choose(c);$('#choices').appendChild(b)}$('#nextBtn').classList.add('hidden')}else $('#nextBtn').classList.remove('hidden');$('#backBtn').disabled=!historyStack.length;const total=DATA.meta.progressSteps||24;$('#progressBar').style.width=Math.min(96,Math.max(2,((historyStack.length+1)/total)*100))+'%';bgFor(state.current,n.time);window.scrollTo({top:0,behavior:'instant'});save()}
function snap(){return JSON.parse(JSON.stringify(state))}function go(next){historyStack.push(snap());state.current=next;state.step=(state.step||0)+1;render()}function next(){const n=currentNode();if(n.end)return finish();if(n.next)go(n.next);else if(state.current==='prolog')go(DATA.startScene)}function choose(c){historyStack.push(snap());Object.assign(state,c.set||{});state.current=c.next;state.step=(state.step||0)+1;render()}function back(){if(!historyStack.length)return;state=historyStack.pop();render()}
function endingKey(){return state.ending||DATA.defaultEnding||Object.keys(DATA.endings)[0]}
function finish(){historyStack.push(snap());stopSpeech();$('#storyScreen').classList.add('hidden');$('#endScreen').classList.remove('hidden');const k=endingKey(),e=DATA.endings[k]||DATA.endings[DATA.defaultEnding];$('#endingTitle').textContent='„'+e.title+'”';$('#endingText').innerHTML=mdToHtml(e.text);$('#routeSummary').textContent=e.route||e.title;$('#routeTeaser').textContent=e.teaser||'';$('#aftercarePanel').classList.add('hidden');$('#whatNextBtn').classList.remove('hidden');$('#progressBar').style.width='100%';state.ending=k;saveShared();save();window.scrollTo(0,0)}
function restart(){if(confirm('Rozpocząć test od początku?')){localStorage.removeItem(storeKey);showStart();renderFlags($('#endingSelect').value)}}function resume(){if(restore()){showStory();render()}}
function textForSpeech(){const el=$('#storyScreen').classList.contains('hidden')?$('#endingText'):$('#storyText');return el?.innerText||''}function stopSpeech(){if('speechSynthesis'in window){speechSynthesis.cancel();speaking=false;$('#audioBtn').textContent='◉'}}function toggleSpeech(){if(!('speechSynthesis'in window))return alert('Ta przeglądarka nie obsługuje narracji systemowej.');if(speaking){stopSpeech();return}const u=new SpeechSynthesisUtterance(textForSpeech());u.lang='pl-PL';u.rate=.92;u.onend=()=>{speaking=false;$('#audioBtn').textContent='◉'};speaking=true;$('#audioBtn').textContent='■';speechSynthesis.speak(u)}
function dims(f){return f==='post'?{w:1080,h:1080}:{w:1080,h:1920}}function wrap(ctx,t,m){const w=String(t||'').split(/\s+/),L=[];let l='';for(const x of w){const q=l?l+' '+x:x;if(ctx.measureText(q).width>m&&l){L.push(l);l=x}else l=q}if(l)L.push(l);return L}function safe(t){return String(t||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'')}
async function card(f='story'){const e=DATA.endings[endingKey()],{w,h}=dims(f),p=h>w,c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,w,h);g.addColorStop(0,'#17120d');g.addColorStop(.5,'#0b1016');g.addColorStop(1,'#040609');x.fillStyle=g;x.fillRect(0,0,w,h);const m=90;x.fillStyle='#d7b46a';x.font='700 30px Arial';x.fillText('TWOJE LEGENDY',m,110);x.fillStyle='#bdb5a8';x.font='600 22px Arial';x.fillText(`PÓŁNOC W HOTELU AURORA · ODCINEK ${DATA.meta.num}`,m,155);x.fillStyle='#f6f0e7';x.font=`500 ${p?76:66}px Georgia`;let y=p?350:280;for(const line of wrap(x,e.title,w-m*2).slice(0,3)){x.fillText(line,m,y);y+=p?88:76}x.fillStyle='#d7b46a';x.font='600 29px Arial';x.fillText(e.route||e.title,m,y+15);y+=100;x.strokeStyle='rgba(215,180,106,.42)';x.strokeRect(m,y,w-m*2,p?390:310);x.fillStyle='#eee6da';x.font=`500 ${p?38:32}px Georgia`;let ty=y+75;for(const line of wrap(x,e.teaser||'',w-m*2-70).slice(0,7)){x.fillText(line,m+35,ty);ty+=p?54:45}x.textAlign='center';x.fillStyle='#fff';x.font='600 25px Arial';x.fillText('Historia zapamiętała Twoje decyzje.',w/2,p?h*.90:h*.90);x.fillStyle='#d7b46a';x.font='700 31px Arial';x.fillText('twojelegendy.pl',w/2,p?h*.955:h*.955);const blob=await new Promise(r=>c.toBlob(r,'image/png',.95));return{blob,filename:`aurora_odcinek_${DATA.meta.num}_${safe(e.title)}_${f}.png`,e}}
async function downloadCard(f){const st=$('#shareStatus');st.textContent='Tworzę kartę…';try{const r=await card(f),u=URL.createObjectURL(r.blob),a=document.createElement('a');a.href=u;a.download=r.filename;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);st.textContent='Karta została pobrana jako PNG.'}catch(e){st.textContent='Nie udało się utworzyć karty.'}}
async function shareCard(){const st=$('#shareStatus');st.textContent='Przygotowuję kartę…';try{const r=await card('story'),file=new File([r.blob],r.filename,{type:'image/png'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title:`Północ w Hotelu Aurora — ${r.e.title}`,text:r.e.teaser,files:[file]});st.textContent='Karta gotowa.'}else{await downloadCard('story')}}catch(e){if(e?.name!=='AbortError')st.textContent='Nie udało się udostępnić karty.'}}
function report(){const lines=[`AURORA — ODCINEK ${DATA.meta.num} — RAPORT TESTU V1`,'',`Bohaterka: ${state.name}`,`Poprzednia ścieżka: ${state.prev}`,`Zakończenie: ${endingKey()}`,''];for(const k of Object.keys(state).filter(k=>/^decision\d+/.test(k)).sort())lines.push(`${k}: ${state[k]||'-'}`);lines.push('','Uwagi:','1. ','2. ','3. ');const blob=new Blob([lines.join('\r\n')],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`AURORA_EP${DATA.meta.num}_RAPORT_TESTU.txt`;a.click()}
$('#startBtn').onclick=startNew;$('#nextBtn').onclick=next;$('#backBtn').onclick=back;$('#restartBtn').onclick=restart;$('#audioBtn').onclick=toggleSpeech;$('#resumeBtn').onclick=resume;$('#againBtn').onclick=()=>{localStorage.removeItem(storeKey);showStart()};$('#reportBtn').onclick=report;$('#downloadStoryBtn').onclick=()=>downloadCard('story');$('#downloadPostBtn').onclick=()=>downloadCard('post');$('#shareCardBtn').onclick=shareCard;$('#whatNextBtn').onclick=()=>{$('#whatNextBtn').classList.add('hidden');$('#aftercarePanel').classList.remove('hidden');setTimeout(()=>$('#aftercarePanel').scrollIntoView({behavior:'smooth',block:'start'}),30)};
initStart();if(localStorage.getItem(storeKey))$('#resumeBtn').classList.remove('hidden');